name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download ffmpeg, zip
      run: sudo apt-get update && sudo apt-get install -y ffmpeg zip
    - name: Create music objects
      run: node build.mjs --verbose
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: "OpenRCT2 OpenMusic Objects"
        path: out/**/*
    - name: Create release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        fail_on_unmatched_files: true
        files: artifacts/openmusic.zip
